import { GoogleGenerativeAI } from "@google/generative-ai";
import * as dotenv from 'dotenv';
import mongoose from 'mongoose';

// Load environment variables FIRST
dotenv.config({ path: '.env.local' });

// Dynamic imports to ensure env vars are loaded before these modules are accessed
const connectDB = require('../lib/mongoose').default;
const { ChatConversation } = require('../models/ChatConversation');
const { generateContentSmart } = require('../lib/gemini-client');

async function analyzeContentGaps() {
    console.log("🔍 Starting Content Gap Analysis...");

    try {
        await connectDB();
        console.log("✅ Connected to MongoDB");

        // 1. Fetch conversations from the last 30 days (to get enough data for this demo)
        const dateLimit = new Date();
        dateLimit.setDate(dateLimit.getDate() - 30);

        const conversations = await ChatConversation.find({
            createdAt: { $gte: dateLimit },
            'messages.role': 'user' // Ensure there are user messages
        }).sort({ createdAt: -1 }).limit(100);

        console.log(`📊 Found ${conversations.length} conversations to analyze.`);

        if (conversations.length === 0) {
            console.log("⚠️ No conversations found. Exiting.");
            process.exit(0);
        }

        // 2. Pre-process data for the LLM
        // We only need the user's questions and the classified intent/category
        const conversationSummary = conversations.map(c => {
            const userMessages = c.messages
                .filter(m => m.role === 'user')
                .map(m => m.content)
                .join(" | ");

            return `
            - Intent: ${c.analytics?.intent || 'unknown'}
            - Category: ${c.analytics?.category || 'general'}
            - User Query: "${userMessages}"
            `;
        }).join("\n");

        // 3. Prompt Gemini to analyze
        console.log("🤖 Sending data to Gemini for analysis...");

        const prompt = `
        Act like a Senior SEO Content Strategist.
        Analyze the following real user search queries and interactions from our chatbot.
        
        GOAL: Identify "Content Gaps" - topics that users are interested in but might not be fully covered or clear on our current website.

        DATA:
        ${conversationSummary}

        OUTPUT FORMAT:
        Please generate a strategic report with the following structure:

        ## 1. Top 3 Missing Topics (High Priority)
        Identify the 3 most requested topics that seem to cause confusion or questions.
        For each:
        - **Topic Name**:
        - **Evidence**: (Quote 1-2 representative user queries)
        - **Action Plan**: Suggest a new Landing Page Title or Blog Post Title to address this.

        ## 2. Low Hanging Fruit (Quick Fixes)
        Identify simple questions that keep repeating and could be solved by adding a sentence to the FAQs or the Homepage.

        ## 3. Sentiment Pulse
        Briefly describe the overall sentiment. Are users frustrated about something specific (e.g., shipping, prices)?

        Keep the report concise and actionable.
        `;

        const report = await generateContentSmart(prompt);

        console.log("\n=======================================================");
        console.log("🚀 CONTENT GAP REPORT (Generated by Gemini)");
        console.log("=======================================================\n");
        console.log(report);
        console.log("\n=======================================================");

    } catch (error) {
        console.error("❌ Error during analysis:", error);
    } finally {
        await mongoose.disconnect();
        process.exit();
    }
}

analyzeContentGaps();
